# Site settings
baseurl = "https://vividtheory.github.io/"
languageCode = "en-us"
title = "Vivid Theory"
theme = "hugo-artists-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Vivid Theory"
	description = "interactive algorithmic installation art"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "vividtheory@gmail.com"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Vivid Theory"
		shortBio = "interactive algorithmic installation art"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About Vivid Theory"
		bio = "Vivid Theory makes digital media art installations for a wide range of audiences.  Underground parties, DJ nights, festivals, maker faires... each setting presents an interesting set of opportunities and challenges.  While visual appeal is important, the primary aim is to produce art that is engaging and thought provoking.  Mathematics and algorithms underly the custom software developed for each installation.  Interactive technology (which could range from a sophisticated 3D sensor to a simple arcade pushbutton) adds a new dimension - the human element.  This mixture of algorithmic expression and interactivity yields some truly amazing effects.  Scroll down to see some examples."
		quote = "Theory underlies the art; the art brings theory to life."
		

	# Contact secion
	#[params.contact]
	#	title = "Contact"
#
#		# The following social network icons are available:
#		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
#		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
#		[[params.contact.social]]
#			icon = "twitter"
#			link = "//twitter.com/devtipsshow"
#
#		[[params.contact.social]]
#			icon = "dribbble"
#			link = "//dribbble.com/travisneilson"
#
#		[[params.contact.social]]
#			icon = "behance"
#			link = "//www.behance.net/travisneilson"
#
#		[[params.contact.social]]
#			icon = "youtube"
#			link = "//www.youtube.com/DevTipsForDesigners"
#
#		[[params.contact.social]]
#			icon = "linkedin"
#			link = "//www.linkedin.com/in/travisneilson"


	[params.form]
		title = "Contact"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Let's talk about it."
		buttonText = "Send"


	[params.footer]
		copyright = "Vivid Theory 2016"
